### ISSUE TITLE
Rename `mine.py` into `wsgi.py`?

### ISSUE THREAD

**Issue by zaibacu** [josephmancuso/masonite#21]
It looks like `mine.py` is basically WSGI file, just named differently. It can be easy way to remove some mist of confusion :)

**Comment by josephmancuso** [comment]
yeah `mine.py` was the first word that popped up in my head when making it. It obviously didn't start as a project that will revolutionize Python web frameworks lol. I'll get on this, unless you want to open a PR. seems like an easy fix. 

- [ ] Change `mine.py` to `wsgi.py`
- [ ] Change reference to it in the Procfile.
- [ ] Find other references to it (via text editor search)
