### ISSUE TITLE
Move start.py into a more commonsense folder name

### ISSUE THREAD

**Issue by josephmancuso** [josephmancuso/masonite#26]
Some folder named kernel maybe? but deeper inside the file structure? Doesn't really matter where it is as long as it makes sense

**Comment by afdolriski** [comment]
What about inside a `bootstrap/` folder ?

**Comment by josephmancuso** [comment]
Yeah that would work. The bootstrap folder can be in the same root location as Laravel bootstrap folder

**Comment by josephmancuso** [comment]
Yeah that would work. The bootstrap folder can be in the same root location as Laravel bootstrap folder

**Comment by josephmancuso** [comment]
@afdolriski if you'd like to put together a Pull Request. Just go ahead and fork the repo, clone it on the your computer, make the change, make a feature branch called "move-start", make your changes, push to your origin feature branch and then come to this repo and create a Pull Request.

**Comment by josephmancuso** [comment]
Completed this
