### ISSUE TITLE
Need a great logo / branding

### ISSUE THREAD

**Issue by josephmancuso** [josephmancuso/masonite#31]
as the framework grows, this framework needs a branding to get on par with other frameworks out there. This needs to be a movement, not just a repo.
 
If anyone is really good at graphic design :)

**Comment by MayaRupa** [comment]
hi @josephmancuso , can i contribute to the visual branding aspect of this project?
so far i've made the visual board on invision app.
https://projects.invisionapp.com/d/main#/projects/boards/5845717

**Comment by josephmancuso** [comment]
Sure, I made some suggestions. I'm not exactly the creative type. Frontend is not my strong suit.
