### ISSUE TITLE
Consider removing Libsass requirement and make sass support optional

### ISSUE THREAD

**Issue by josephmancuso** [josephmancuso/masonite#32]
right now the SASS support is built in but the libsass library takes a long time to install.

consider either:

* sticking it out as the only time the dev has to wait is when creating a project
* make an environment variable to set SASS to a bool so the `masonite.storage.compile_sass`
 method is not ran without the package installed

OR only run if the libsass package is installed. This could be really good since the developer just needs to pip install libsass and nothing else to unlock full support of sass

**Comment by afdolriski** [comment]
I think the sass feature is not always needed especially when it comes to make an api.

So the option is:
* Make it unavailable by default, but provide an option to make it available, it could be in the .env file or any other file. Or..
* Make a dialog to gather informations about the project requirement when user run the ```craft new project``` command, and based on that informations make all of the optional features becomes available.

**Comment by josephmancuso** [comment]
@afdolriski I think inside the `bootstrap/start.py` file on line 16 https://github.com/josephmancuso/masonite/blob/master/bootstrap/start.py#L16 we do something like:

```
try:
    Storage().compile_sass()
except ImportError as e:
    pass
```

This way it will only work if the needed imports are in.

Masonite is not going to be like other frameworks. With this solution we will leave out libsass by default but `pip install libsass` will activate the sass integration of the app. I think a lot of people, including myself, don't use sass because the setup seems complex to me.

This needs to be a 1 command activation and MAYBE some configuration if it makes total sense.

**Comment by afdolriski** [comment]
That looks good.

So the libsass will be removed from ```requirements.txt``` file ? And the sass support will be available only if the developer has libsass package installed ?

**Comment by josephmancuso** [comment]
correct

**Comment by afdolriski** [comment]
can i remove it ?

**Comment by josephmancuso** [comment]
Yes. Put the PR into the v0.3.1 branch as that'll be the next release

**Comment by josephmancuso** [comment]
Remove that requirement, put the try around the masonite. pip uninstall libsass and see if any errors are thrown

**Comment by afdolriski** [comment]
It gives an error, because this file https://github.com/josephmancuso/masonite-core/blob/master/masonite/storage.py importing the sass module.
But i find another way, keep the line https://github.com/josephmancuso/masonite/blob/master/bootstrap/start.py#L16 as it is, but use the try clause in https://github.com/josephmancuso/masonite-core/blob/master/masonite/storage.py#L11 instead inside the ```def compile_sass():``` method to import the sass module. it gives no error and no css file compiled.

**Comment by josephmancuso** [comment]
so wrap the whole contents of the `compile_sass():` function in a try catch block?

**Comment by josephmancuso** [comment]
I'm not a huge fan of wrapping an entire function with a try catch but what you could do is something like:

```
def compile_sass():
    try:
        import sass
    except ImportError as e:
        return None

    ... rest of function here ...
```

**Comment by afdolriski** [comment]
That's actually what i mean..
But mine is slightly different..
```python
def compile_sass():
    try:
         import sass
    except ImportError as e:
         pass
    else:
         # the rest...
```
What do you think ?
I think this way would be more flexible.

**Comment by josephmancuso** [comment]
Yeah that's good. I like it
