### ISSUE TITLE
Create Oauth Implementation.

### ISSUE THREAD

**Issue by afdolriski** [josephmancuso/masonite#36]
Since it is the industry-standard protocol for authorization.

**Comment by josephmancuso** [comment]
Yeah. This is a really good idea and on the list. I say we brand our official packages. Laravel framework calls this "Laravel Socialite". 

If this means what I think it means (adding third party oauth capabilities) then it should probably resemble Laravel capabilities. https://laravel.com/docs/5.5/socialite I think this will be a good fit for this framework. Notice how they use the controllers for sending and receiving oauth requests and responses

**Comment by josephmancuso** [comment]
sidenote, this may be in version 0.3.2

**Comment by josephmancuso** [comment]
Currently patch versions while under `v1` will act like minor versions. There should be at least some third party package support or some development for patch versions

**Comment by josephmancuso** [comment]
I'll keep this open but this should be an Official Package

**Comment by josephmancuso** [comment]
https://github.com/josephmancuso/masonite-authhub
