### ISSUE TITLE
Unclear explanation in CONTRIBUTING.md

### ISSUE THREAD

**Issue by afdolriski** [josephmancuso/masonite#37]
On https://github.com/josephmancuso/masonite/blob/master/CONTRIBUTING.md on the getting started section it says :

**This** repository will be updated based on **this** repository

What is this actually mean ?

**Comment by josephmancuso** [comment]
yeah so anything file structure related will go here.

any changes you need to make to the core of the project (`masonite` packages) can be found in josephmancuso/masonite-core. These changes include things like extending the `Request()` object, routes, apis, strorage etc. 

It depends on the change you want to make

**Comment by josephmancuso** [comment]
added documentation link to CONTRIBUTING.md to show how the software works
