### ISSUE TITLE
Error ModuleNotFoundError: No module named 'mine'

### ISSUE THREAD

**Issue by afdolriski** [josephmancuso/masonite#38]
This error happen when i try to run ```craft serve``` command, i think this problem has something to do with changes in ```mine.py``` to ```wsgi.py``` but i didn't find where the code is executed.

![screenshot from 2018-01-11 01-06-30](https://user-images.githubusercontent.com/25895176/34788099-30f46f24-f66c-11e7-93ee-f5ec7d6deafa.png)

**Comment by josephmancuso** [comment]
which version of masonite-cli are you running?

**Comment by josephmancuso** [comment]
this should have been fixed in newer versions. You may have to try running `craft new` again to get the latest changes to the project as well as running `pip install --upgrade masonite-cli`

**Comment by afdolriski** [comment]
Running ```pip install --upgrade masonite-cli``` solve the problem, thanks!
