### ISSUE TITLE
Official Package Ideas

### ISSUE THREAD

**Issue by josephmancuso** [josephmancuso/masonite#40]
Please list all ideas for official packages that will integrate directly within Masonite.

On names subject to change

### 

- [x] Masonite Clerk

[Repo found here](https://github.com/josephmancuso/masonite-clerk)

[Docs found here](https://github.com/josephmancuso/masonite/blob/v0.3.1/docs/Masonite-Clerk.md)

This will be a package that allows adding subscriptions to users. This will only work with the default Orator ORM. The simple setup will be similar to [Laravels Cashier](https://laravel.com/docs/5.5/billing)

* extending the user model with a class that contains additional methods
    * `subscribe()`,`subscribedToPlan()`,`unsubscribe()`, `charge()`
* simple copy and paste migrations
* the new `craft publish` command which will be available in `masonite-cli==0.30`

- [x] Masonite AuthHub

Simple integration support for third party oauth services. Will come with the GitHub driver but can be used with other drivers as well like Facebook, Twitter, LinkedIn

**Comment by afdolriski** [comment]
## Database seeder or something like factory

An integration to the database that make seeder and generate random data easily to the database.
## Artisan tinker like repl

It will be a very useful to messing around with the database and the application itself.

**Comment by josephmancuso** [comment]
@afdolriski I think the artisan tinker command is the same as the `python shell` shell? right?

**Comment by afdolriski** [comment]
Yeah that's true, i mean for example when we want to interact with our orm to perform an operation to the database in `artisan tinker` it's already enabled but when using flask we need to use` app_context()` to do that, is that kind of functionality already available with only python shell ?

**Comment by josephmancuso** [comment]
I'm going to experiment with this idea. Somehow we need to load models into a python shell

**Comment by josephmancuso** [comment]
### Masonite Trigger

Add trigger support for masontite to register and trigger classes and methods with 1 line.
