### ISSUE TITLE
Internal Server Error  The server encountered an unexpected internal server error  (generated by waitress)

### ISSUE THREAD

**Issue by afdolriski** [josephmancuso/masonite#46]
This is my stacktrace

![screenshot from 2018-01-12 22-48-42](https://user-images.githubusercontent.com/25895176/34883006-dbf9077a-f7ea-11e7-964a-13708b0cbc8b.png)

**Comment by josephmancuso** [comment]
Try running `python -m pytest`

**Comment by afdolriski** [comment]
i have tried to reinstall the masonite-cli package but it didn't work, my solution is to change my venv to 3.5 and installing again the masonite-cli package then it works perfect.

**Comment by josephmancuso** [comment]
What version were you on with both

**Comment by josephmancuso** [comment]
The framework is growing rapidly and under version 1 so things may break. I need to write more tests to ensure

**Comment by josephmancuso** [comment]
Just always make sure everything is up to date

**Comment by afdolriski** [comment]
It was on the same version, the only difference i found is that on `python3.5/site-packages/` folder the masonite package folders ends with `.egg-info` while on the `python3.6/site-packages/` the folder names ends with `.dist-info`

**Comment by josephmancuso** [comment]
weird, can you try and run it back on python3.6 by any chance?

**Comment by afdolriski** [comment]
I already tried that and the test gives no error

**Comment by josephmancuso** [comment]
hmm I'm gonna chalk this up to an anomaly maybe and reopen if someone comes across this issue again.
