### ISSUE TITLE
(1071, 'Specified key was too long; max key length is 767 bytes')

### ISSUE THREAD

**Issue by ondoheer** [josephmancuso/masonite#49]
As in Laravel, if a system hasn't been properly configured, this error will popup. In Laravel you do [a simple hack](https://laravel-news.com/laravel-5-4-key-too-long-error) and it will overwritte the default length of VARCHAR. How do you do this in Masonite? I explicitely set the chars length in the User migration file:

```
table.string('email', 191).unique()
```

**Comment by josephmancuso** [comment]
let me look. Masonite uses Orator so lets see if there is a solution to that

**Comment by josephmancuso** [comment]
awaiting response from Orator
