### ISSUE TITLE
Inspirational frameworks arround the web

### ISSUE THREAD

**Issue by Marlysson** [josephmancuso/masonite#62]
I was seeing the frameworks's code and I notice a similarity with Laravel ( routes structures, some content's issues.. ) . Do your bigger inspiration to this frameworks is Laravel?

Do you already have next steps to this frameworks as features, requests more critical..

Good framework, congratulations.

**Comment by josephmancuso** [comment]
Yes, I draw a lot of inspiration from Laravel. I honestly think it's a tremendous framework and what to bring something similar to Python.
